### ISSUE TITLE
master branch exists

### ISSUE THREAD

**Issue by Bergenfrundt** [Bergenfrundt/WHATSGOINGONINHERE#1]
please deleterino someone

**Comment by cherche** [comment]
Go to Code tab, press "Branches", delete.

**Comment by Bergenfrundt** [comment]
isn't there

i'm using github web exclusively that's probably why

**Comment by cherche** [comment]
![screen shot 2016-02-16 at 5 37 13 pm](https://cloud.githubusercontent.com/assets/12107277/13093901/9d0cdb20-d4d5-11e5-9537-6807356c20be.png)

**Comment by Bergenfrundt** [comment]
gotem
